services:
  frontend:
    image: 'ghcr.io/jezreal/cats_fs'
    ports:
      - '3000:3000'
    env_file:
      - .env.prod

  database:
    image: 'postgres'
    env_file:
      - .env.prod
    volumes:
      - cats-volume:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  cats-volume:
